### ISSUE TITLE
Menu Displayed instead of Placeholder — Endpoint for meals

### ISSUE THREAD

**Issue by shivanimadhan** [ucsb-cs156-f24/proj-dining-f24-13#13]
Create a service that will get all of the meals served in a particular dining commons on a particular date

Using the api endpoint described here: https://developer.ucsb.edu/apis/dining/dining-menu

Then build a controller endpoint /api/diningcommons/:date-time/:dining-commons-code the returns this information.

**Comment by clevermonkey16** [comment]
Note: Should probably wait until #8 is done so that we can use the same controller file
